### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by JokerQyou** [JokerQyou/ethbot#1]
Following things need to be done before publishing the code:
- [ ] Single pre-release script
- [ ] Tutorial of deployment
- [x] Hard-coded value cleaning
- [x] Package reform

**Comment by JokerQyou** [comment]
Consider this a personal service, currently there is no plan of open source.

**Comment by JokerQyou** [comment]
Not going to fix.
